# Generated by Django 6.1.1 on 2026-09-07 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffViaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("EMPACADOR", "Empacador"),
                            ("VIAJERO", "Viajero"),
                            ("DISTRIBUIDOR", "Distribuidor"),
                            ("REPARTIDOR", "Repartidor"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff del Viaje",
                "verbose_name_plural": "Staff del Viaje",
            },
        ),
        migrations.RemoveConstraint(
            model_name="participanteviaje",
            name="unique_usuario_rol_viaje",
        ),
        migrations.AlterField(
            model_name="envio",
            name="estado_entrega",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ENVIADO", "Enviado"),
                    ("RECIBIDO", "Recibido"),
                    ("ENTREGADO", "Entregado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="sku",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="StaffViaje",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="StaffViaje",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="StaffViaje",
            name="viaje",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="StaffViaje",
                to="delivery.viaje",
            ),
        ),
        migrations.RemoveField(
            model_name="participanteviaje",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="participanteviaje",
            name="viaje",
        ),
        migrations.AddConstraint(
            model_name="StaffViaje",
            constraint=models.UniqueConstraint(
                fields=("viaje", "usuario", "rol"), name="unique_usuario_rol_viaje"
            ),
        ),
        migrations.DeleteModel(
            name="ParticipanteViaje",
        ),
    ]
