# Generated by Django 6.1.1 on 2026-09-08 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_staffviaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffviaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_viajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffviaje',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='delivery.viaje'),
        ),
    ]
